[package]
name = "evm-state"
version = "0.1.0"
authors = ["Vladimir Motylenko <vld@stegos.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evm = { version = "0.18", features = ["with-serde"] }
secp256k1 = { version = "0.19.0", features = ["recovery", "global-context"] }
# force rand version, because 0.6.5 break compatibility with secp256k1
rand2 = { version = "=0.6.1", package = "rand" }
rocksdb = { version = "0.15.0", default-features = false }

primitive-types = "0.7.2"
keccak-hash = "0.5"
log = "0.4"
simple_logger = "1.11"
hex = "0.4.2"
serde = "1.0"
sha3 = "0.9.1"
assert_matches = "1.4"
rand = "0.7.3"
rlp = "0.4.5"
thiserror = "1.0.22"
anyhow = "1.0.34"
bincode = "1.3.1"
lazy_static = "1.4.0"
bytes = "0.6.0"


[dev-dependencies]
criterion = "0.3"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
rand = "0.7.3"
paste = "1.0.3"

[[bench]]
name = "bench_evm"
harness = false
