name: Tests

on: 
  pull_request:
    branches: [develop]
  schedule:
    - cron: "0 10 * * *"

jobs:  
  checks:
    name: check
    runs-on: build
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: install dependencies
        run: |
          apt-get update
          apt-get -y install curl git libssl-dev libudev-dev make pkg-config zlib1g-dev llvm clang      
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -Dwarnings
  test:
    name: test
    runs-on: build
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: install dependencies
        run: |
          apt-get update
          apt-get -y install curl git libssl-dev libudev-dev make pkg-config zlib1g-dev llvm clang jq zsh wget
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x /usr/local/bin/yq
      - name: Run cargo test
        run: scripts/cargo-test-group.sh default

