name: Tests

on: 
  pull_request:
    branches: [develop]
  schedule:
    - cron: "0 10 * * *"

jobs:  
  checks:
    name: check
    container:
      image: ubuntu:20.04
    runs-on: build
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive  apt-get -q -y install curl git libssl-dev libudev-dev make pkg-config zlib1g-dev llvm clang      
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.55
          components: clippy
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -Dwarnings
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get -q -y install curl git libssl-dev libudev-dev make pkg-config zlib1g-dev llvm clang      
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.55
      - name: Setting limits
        run: |
          sudo sysctl -w fs.file-max=5000000
          sudo sysctl -w vm.max_map_count=5000000
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

